services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:mysecret@postgres-db:5432/postgres
      - ALLOWED_ORIGINS=http://localhost:5173,http://127.0.0.1:5173
    depends_on:
      - postgres-db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://backend:3000/api/v1
    depends_on:
      - backend

  postgres-db:
    image: postgres:15
    environment:
      - POSTGRES_PASSWORD=mysecret
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: